/* 
 * File:   gui_scheme.h
 * Author: trol
 *
 * Created on 31 ÿםגאנÿ 2017 ד., 20:28
 */

#ifndef _GUI_SCHEME_H_
#define _GUI_SCHEME_H_

#define SCREEN_FONT
#define SCREEN_TITLE_COLOR						0xFFFF
#define SCREEN_TITLE_BACKGROUND				0x0016
#define SCREEN_BUTTONS_COLOR					0xE71A
#define SCREEN_BUTTONS_BACKGROUND			0x2168

#define LIST_FONT
#define LIST_BACKGROUND							0xD75F
#define LIST_ITEM_COLOR							0x0000
#define LIST_SELECTION_BACKGROUND			0xA5DF
#define LIST_SELECTION_COLOR					0x0000

#define PROGRESSBAR_FRAME_COLOR				0x0000
#define PROGRESSBAR_BACKGROUND				0xffff
#define PROGRESSBAR_FILL_BACKGROUND			0x3A5A
#define PROGRESSBAR_SEGMENT_WIDTH			5
#define PROGRESSBAR_SEGMENT_GAP				2

#define SCROLLBAR_BACKGROUND					0xD75F
#define SCROLLBAR_SLIDER_BACKGROUND			0x3198
#define SCROLLBAR_SLIDER_BACKGROUND_ALT	0x7998	//0x33F8
#define SCROLLBAR_SLIDER_COLOR_1				0x4A9F
#define SCROLLBAR_SLIDER_COLOR_2				0x212F
#define SCROLLBAR_LINE_COLOR					0x0311


#endif // _GUI_SCHEME_H_

